project_id = "eynulvphjcojanzryfyi"

[functions.create-employee]
verify_jwt = false

[functions.delete-employee]
verify_jwt = false

[functions.update-employee-password]
verify_jwt = false

[functions.auto-punch-in]
verify_jwt = false

[functions.auto-temperature-logs]
verify_jwt = false

[functions.auto-punch-out]
verify_jwt = false
